### ISSUE TITLE
Binding C-S-m and the like

### ISSUE THREAD

**Issue by fikovnik** [CyberShadow/term-keys#6] opened 2019-05-11 13:44 UTC
I guess having `C-m` to be completely free won't be possible in terminal, but I was wondering if `C-S-m` could be somehow use since it now sends `^[^_Jc^_`. AFAIK, the trick is to somehow convince emacs not to map `C-m` to `RET` virtual key. Is there any way?

btw: the same applies to `C-j` and `C-i`

**Comment by CyberShadow** [comment] 2019-05-11 13:54
- `C-m` can be rebound if you enable translation for it in the terminal map term-keys generates;
- `C-S-m` is translated by default, as you've noticed;
- Off the top of my head, I don't know / remember how to make Emacs distinguish between the two. It is generally the same issue as distinguishing between `RET` and `C-m` in X11 frames, which is somewhat out of scope for `term-keys`.

**Comment by fikovnik** [comment] 2019-05-11 15:31
Thank you. It turned out that to bind these keys one has to use a symbol vector instead of `kbd` macro in the define-key. For example to bind the `C-S-m`:

```
(define-key input-decode-map "\033\037Jc\037" [C-M])
```

So, I was wrong, there is no need to tell Emacs anything else. Given this I think it is in the scope of term-keys, but of course, feel free to close this if you don't think you want to support it.

**Comment by CyberShadow** [comment] 2019-05-11 15:46
Interesting, thanks for sharing. `term-keys` calls `(define-key input-decode-map "\033\037Jc\037" (kbd "S-C-m"))`, which I would think would be the same as `[C-M]`, but if the above works for you, apparently is not. I'll need to look into whether `term-keys` even needs to use `kbd` at all.

**Comment by CyberShadow** [comment] 2021-12-28 15:36
So, I experimented with this a bit. I'm not sure I can get it to work.

First, the term-keys patch is simple enough:

```diff
diff --git a/term-keys.el b/term-keys.el
index 1029068..5c85fa9 100644
--- a/term-keys.el
+++ b/term-keys.el
@@ -48,22 +48,22 @@ file."
 
 
 (defcustom term-keys/mapping
-  '(["<escape>"		"Escape"	1	"Esc"		#x001B	]
-    ["<f1>"		"F1"		59	"F1"		#xF704	]
-    ["<f2>"		"F2"		60	"F2"		#xF705	]
-    ["<f3>"		"F3"		61	"F3"		#xF706	]
-    ["<f4>"		"F4"		62	"F4"		#xF707	]
-    ["<f5>"		"F5"		63	"F5"		#xF708	]
-    ["<f6>"		"F6"		64	"F6"		#xF709	]
-    ["<f7>"		"F7"		65	"F7"		#xF70A	]
-    ["<f8>"		"F8"		66	"F8"		#xF70B	]
-    ["<f9>"		"F9"		67	"F9"		#xF70C	]
-    ["<f10>"		"F10"		68	"F10"		#xF70D	]
-    ["<f11>"		"F11"		87	"F11"		#xF70E	]
-    ["<f12>"		"F12"		88	"F12"		#xF70F	]
-    ["<print>"		"Print"		99	"Print"		#xF710	]
-    ["<Scroll_Lock>"	"Scroll_Lock"	70	"ScrollLock"	nil	]
-    ["<pause>"		"Pause"		119	"Pause"		nil	]
+  '(["escape"		"Escape"	1	"Esc"		#x001B	]
+    ["f1"		"F1"		59	"F1"		#xF704	]
+    ["f2"		"F2"		60	"F2"		#xF705	]
+    ["f3"		"F3"		61	"F3"		#xF706	]
+    ["f4"		"F4"		62	"F4"		#xF707	]
+    ["f5"		"F5"		63	"F5"		#xF708	]
+    ["f6"		"F6"		64	"F6"		#xF709	]
+    ["f7"		"F7"		65	"F7"		#xF70A	]
+    ["f8"		"F8"		66	"F8"		#xF70B	]
+    ["f9"		"F9"		67	"F9"		#xF70C	]
+    ["f10"		"F10"		68	"F10"		#xF70D	]
+    ["f11"		"F11"		87	"F11"		#xF70E	]
+    ["f12"		"F12"		88	"F12"		#xF70F	]
+    ["print"		"Print"		99	"Print"		#xF710	]
+    ["Scroll_Lock"	"Scroll_Lock"	70	"ScrollLock"	nil	]
+    ["pause"		"Pause"		119	"Pause"		nil	]
 
     ["`"		"grave"		43	"`"		?`	]
     ["1"		"1"		2	"1"		?1	]
@@ -78,8 +78,8 @@ file."
     ["0"		"0"		11	"0"		?0	]
     ["-"		"minus"		12	"-"		?-	]
     ["="		"equal"		13	"="		?=	]
-    ["<backspace>"	"BackSpace"	14	"Backspace"	#x007F	]
-    ["<tab>"		"Tab"		15	"Tab"		#x0009	]
+    ["backspace"	"BackSpace"	14	"Backspace"	#x007F	]
+    ["tab"		"Tab"		15	"Tab"		#x0009	]
     ["q"		"q"		16	"Q"		?q	]
     ["w"		"w"		17	"W"		?w	]
     ["e"		"e"		18	"E"		?e	]
@@ -92,8 +92,8 @@ file."
     ["p"		"p"		25	"P"		?p	]
     ["["		"bracketleft"	26	"["		?\[	]
     ["]"		"bracketright"	27	"]"		?\]	]
-    ["<return>"		"Return"	28	"Return"	#x000D	]
-    ["<Caps_Lock>"	"Caps_Lock"	58	"CapsLock"	nil	]
+    ["return"		"Return"	28	"Return"	#x000D	]
+    ["Caps_Lock"	"Caps_Lock"	58	"CapsLock"	nil	]
     ["a"		"a"		30	"A"		?a	]
     ["s"		"s"		31	"S"		?s	]
     ["d"		"d"		32	"D"		?d	]
@@ -124,20 +124,20 @@ file."
     ["SPC"		"space"		57	"Space"		#x0020	]
     [nil		"Alt_R"		100	"Alt"		nil	]
     [nil		"Super_R"	126	"Meta"		nil	]
-    ["<menu>"		"Menu"		127	"Menu"		#x0010	]
+    ["menu"		"Menu"		127	"Menu"		#x0010	]
     [nil		"Ctrl_R"	97	"Ctrl"		nil	]
 
-    ["<up>"		"Up"		103	"Up"		#xF700	]
-    ["<down>"		"Down"		108	"Down"		#xF701	]
-    ["<left>"		"Left"		105	"Left"		#xF702	]
-    ["<right>"		"Right"		106	"Right"		#xF703	]
+    ["up"		"Up"		103	"Up"		#xF700	]
+    ["down"		"Down"		108	"Down"		#xF701	]
+    ["left"		"Left"		105	"Left"		#xF702	]
+    ["right"		"Right"		106	"Right"		#xF703	]
 
-    ["<insert>"		"Insert"	110	"Ins"		#xF746	]
-    ["<delete>"		"Delete"	111	"Del"		#xF728	]
-    ["<home>"		"Home"		102	"Home"		#xF729	]
-    ["<end>"		"End"		107	"End"		#xF72B	]
-    ["<prior>"		"Prior"		104	"PgUp"		#xF72C	]
-    ["<next>"		"Next"		109	"PgDown"	#xF72D	]
+    ["insert"		"Insert"	110	"Ins"		#xF746	]
+    ["delete"		"Delete"	111	"Del"		#xF728	]
+    ["home"		"Home"		102	"Home"		#xF729	]
+    ["end"		"End"		107	"End"		#xF72B	]
+    ["prior"		"Prior"		104	"PgUp"		#xF72C	]
+    ["next"		"Next"		109	"PgDown"	#xF72D	]
 
     ;; Add new entries at the end of the list, to avoid disrupting
     ;; existing configurations.
@@ -402,8 +402,10 @@ Collect FUN's return values in a list and return it."
 	term-keys/prefix
 	(term-keys/encode-key index mods)
 	term-keys/suffix)
-       (kbd (term-keys/format-key
-	     (elt keymap 0) mods))))))
+       (vector
+	(make-symbol
+	 (term-keys/format-key
+	  (elt keymap 0) mods)))))))
 
 
 ;;;###autoload
```

And, the keys do get transmitted and decoded correctly (e.g. <kbd>Control+m</kbd> is decoded as `<C-m>`).

The problem is that e.g. `<C-a>` (which is synonymous with `C-<a>`) is a different key from `C-a`. So, none of the alphanumeric bindings defined by default and in typical configuration files will work.

It could work with some elbow grease from the Emacs configuration side, by requiring from users that for every binding such as `C-x`, the same action is also registered as `<C-x>` - one for GUI, and one for the terminal (term-keys). But, that doesn't seem to be very practical.

Perhaps it's doable by modifying the Emacs keybinding machinery so that it treats `<C-x>` and `C-x` in the same way, but also such that it does not conflate `C-M` / `<C-m>` with `RET`, but I imagine this would be non-trivial and perhaps brittle.

So, I'm going to close this issue for now... but feel free to post any ideas if there's a way to make this practical.

**Closed as completed by CyberShadow** 2021-12-28 15:36 UTC
